# Пример №1
## Установка пакетов на Debian
- name: app install Debian
  apt:
    name:
      - curl
      - wget
      - htop
      - sudo
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# Пример №2
## Установка пакетов на Centos
- name: app install Centos
  yum:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: 
    - '{{ packages }}'
  when: ansible_os_family == "RedHat"