# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"


Vagrant.configure(2) do |config|
  # ПЕРВАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "test-server-1" do |server|
    # имя виртуальной машины
    server.vm.box = 'vedoff/centos-7-5' 
    server.vm.provider "virtualbox" do |vb|
      vb.name = "test-server-1"
    end
    # hostname виртуальной машины
    server.vm.hostname = "test-server-1"
    # настройки сети
    server.vm.network "private_network", ip: "192.168.56.80"
    server.vm.synced_folder ".", "/vagrant",  
          type: "rsync",
          rsync_auto: "true",
          rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
    end

 config.vm.define "test-server-2" do |server2|
    # имя виртуальной машины
    server2.vm.box = 'debian11/v1230.1' 
    server2.vm.provider "virtualbox" do |vb|
      vb.name = "test-server-2"
    end
    # hostname виртуальной машины
    server2.vm.hostname = "test-server-2"
    # настройки сети
    server2.vm.network "private_network", ip: "192.168.56.81"
    server2.vm.synced_folder ".", "/vagrant",  
          type: "rsync",
          rsync_auto: "true",
          rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
          #odoo.vm.provision "shell", path: "provision/prepare-host.sh"
# ssh-pub add in server
config.vm.provision "shell", inline: <<-SHELL
cat /vagrant/provision/vagrant-key.pub >> /home/vagrant/.ssh/authorized_keys
SHELL
    end
end
